include: package:lints/recommended.yaml

analyzer:
  errors:
    todo: ignore

linter:
  rules:
    - always_declare_return_types
    - avoid_dynamic_calls
    - comment_references
    - directives_ordering
    - library_annotations
    - only_throw_errors
    - prefer_relative_imports
    - prefer_single_quotes
    - sort_pub_dependencies
