name: builder
description: Performs build operations for google/flutter-mediapipe.

publish_to: none

environment:
  sdk: ^3.1.5

dependencies:
  args: ^2.4.2
  http: ^1.1.0
  io: ^1.0.4
  logging: ^1.2.0
  native_assets_cli: ^0.3.2
  path: ^1.8.0
  process: ^5.0.0

dev_dependencies:
  ffigen: ^9.0.1
  lints: ^2.1.0
  test: ^1.24.0
