include: ../analysis_options.yaml

linter:
  rules:
    - public_member_api_docs # see https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#documentation-dartdocs-javadocs-etc

analyzer:
  exclude:
    - "**/mediapipe_genai_bindings.dart"
