name: mediapipe_genai
description: Provides access to MediaPipe's inference-based ODML tasks.
version: 0.0.1

repository: https://github.com/google/flutter-mediapipe
issue_tracker: https://github.com/google/flutter-mediapipe/issues

platforms:
  android:
  ios:
  # linux:
  macos:
  # web:
  # windows:

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  async: ^2.11.0
  equatable: ^2.0.5
  ffi: ^2.1.0
  flutter:
    sdk: flutter
  http: ^1.1.0
  logging: ^1.2.0
  mediapipe_core: ^0.0.1
  native_assets_cli: ^0.3.0
  native_toolchain_c: ^0.3.0
  path: ^1.8.3

dev_dependencies:
  ffigen: ^9.0.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
