name: mediapipe_text
description: An implementation of MediaPipe text-based Tasks.
version: 0.0.1

repository: https://github.com/google/flutter-mediapipe/tree/main/packages/mediapipe-task-text
issue_tracker: https://github.com/google/flutter-mediapipe/issues/

platforms:
  android:
  ios:
  # linux:
  macos:
  # web:
  # windows:

environment:
  # For now, `native-assets` is a Flutter experiment, which can only be
  # enabled on the `master` channel.
  sdk: ^3.4.0

dependencies:
  async: ^2.11.0
  ffi: ^2.1.2
  http: ^1.1.0
  logging: ^1.2.0
  mediapipe_core: ^0.0.1
  native_assets_cli: ^0.6.0
  native_toolchain_c: ^0.4.2
  path: ^1.8.3

dev_dependencies:
  ffigen: ^12.0.0
  flutter_lints: ^2.0.0
  test: ^1.21.0
